- name: Installing Heat
  action: apt pkg={{item}} state=installed
  with_items:
    - heat-api
    - heat-api-cfn
    - heat-engine
    - python-heatclient
  register: heat_installed

- name: Stopping Heat API
  service: name=heat-api state=stopped
  when: heat_installed|changed
  register: api_stopped

- name: Stopping Heat API CFN
  service: name=heat-api-cfn state=stopped
  when: heat_installed|changed
  register: api_cfn_stopped

- name: Stopping Heat Engine
  service: name=heat-engine state=stopped
  when: heat_installed|changed
  register: engine_stopped

- name: Removing non-used sqlite database
  file: path=/var/lib/heat/heat.sqlite state=absent
  when: heat_installed|changed
  register: heat_cleaned

- name: Updating heat.conf
  template: src=heat.conf
        dest=/etc/heat/heat.conf
        owner=heat
        group=heat
        mode=0640
        backup=yes
  when: heat_installed|changed and item.os_project == "heat"
  with_items: mysql_databases
  register: heat_cfg_updated

- name: Populating Heat Database
  shell: su -s /bin/sh -c "heat-manage db_sync" heat
  register: heat_populated
  when: heat_cfg_updated|changed

- name: Starting Heat API
  service: name=heat-api state=restarted
  when: heat_populated|changed
  register: api_started

- name: Starting Heat API CFN
  service: name=heat-api-cfn state=restarted
  when: heat_populated|changed
  register: api_cfn_stopped

- name: Starting Heat Engine
  service: name=heat-engine state=restarted
  when: heat_populated|changed
  register: engine_started
