# Copyright 2016, Sandvine Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Installing Cinder Server
  action: apt pkg={{item}} state=installed
  with_items:
    - cinder-api
    - cinder-scheduler
  register: cinder_installed

- name: Stopping Cinder API
  service: name=cinder-api state=stopped
  when: cinder_installed|changed
  register: api_stopped

- name: Stopping Cinder Registry
  service: name=cinder-scheduler state=stopped
  when: cinder_installed|changed
  register: registry_stopped

- name: Removing non-used sqlite database
  file: path=/var/lib/cinder/cinder.sqlite state=absent
  when: cinder_installed
  register: cinder_cleaned



- name: Updating cinder.conf
  template: src=cinder.conf
        dest=/etc/cinder/cinder.conf
        owner=cinder
        group=cinder
        mode=0640
        backup=yes
  when: api_stopped|changed and registry_stopped|changed and item.os_project == "cinder"
  with_items: mysql_databases
  register: cinder_cfg_updated


- name: Populating Cinder Database
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
  when: cinder_cfg_updated|changed
  register: cinder_populated

- name: Starting Cinder API
  service: name=cinder-api state=restarted
  when: cinder_populated|changed
  register: apt_started

- name: Starting Cinder Registry
  service: name=cinder-scheduler state=restarted
  when: cinder_populated|changed
  register: registry_started
