- name: Installing Neutron  Agents
  action: apt pkg={{item}} state=installed
  with_items:
    - neutron-plugin-ml2
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - openvswitch-switch
    - neutron-plugin-openvswitch-agent
  register: neutron_installed

- name: Stopping Neutron  Agents
  command: "{{item}}"
  with_items:
    - service neutron-dhcp-agent stop
    - service neutron-l3-agent stop
    - service neutron-metadata-agent stop
    - service neutron-openvswitch-agent stop
  ignore_errors: yes
  when: neutron_installed|changed
  register: neutron_stopped

- name: Updating neutron.conf
  template: src=neutron.conf
            dest=/etc/neutron/neutron.conf
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: neutron_stopped|changed
  with_items: mysql_databases
  register: neutron_cfg_updated

- name: Updating ml2_conf.ini for Open vSwitch
  template: src=ml2_conf.ini_ovs
            dest=/etc/neutron/plugins/ml2/ml2_conf.ini
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: neutron_stopped|changed
  register: ml2_cfg_ovs_updated

- name: Updating ovs agent file for Open vSwitch
  template: src=ml2_conf.ini_ovs
            dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
            owner=root
            group=neutron
            mode=0640
            backup=yes
  when: neutron_stopped|changed
  register: ml2_cfg_ovs_updated

- name: Updating dhcp_agent.ini
  template: src=dhcp_agent.ini
            dest=/etc/neutron/dhcp_agent.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  when: neutron_stopped|changed
  register: dhcpa_cfg_updated

- name: Updating dnsmasq-neutron.conf
  copy: src=dnsmasq-neutron.conf
        dest=/etc/neutron/dnsmasq-neutron.conf
        owner=root
        group=neutron
        mode=0644
        backup=yes
  when: neutron_stopped|changed
  register: dnsmasqn_cfg_updated

- name: Updating l3_agent.ini
  template: src=l3_agent.ini
            dest=/etc/neutron/l3_agent.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  when: neutron_stopped|changed
  register: l3a_cfg_updated

- name: Updating metadata_agent.ini
  template: src=metadata_agent.ini
            dest=/etc/neutron/metadata_agent.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  when: neutron_stopped|changed
  register: metadata_cfg_updated

- name: Updating fwaas_driver.ini
  template: src=fwaas_driver.ini
            dest=/etc/neutron/fwaas_driver.ini
            owner=root
            group=neutron
            mode=0644
            backup=yes
  when: neutron_stopped|changed
  register: fwaasd_cfg_updated

- name: Starting Neutron  Agents
  command: "{{item}}"
  with_items:
    - service neutron-dhcp-agent restart
    - service neutron-l3-agent restart
    - service neutron-metadata-agent restart
    - service neutron-openvswitch-agent restart
  when: fwaasd_cfg_updated and metadata_cfg_updated and l3a_cfg_updated and dnsmasqn_cfg_updated and dhcpa_cfg_updated
  register: neutron_started

- name: Wait a bit until Neutron starts up properly...
  pause: seconds=5
  when: neutron_started|changed
  register: neutron_ready

- name: Write custom sysctl.conf
  copy: src=sysctl.conf
        dest=/etc/sysctl.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - Reload sysctl
