- name: Creating OpenStack Endpoint
  environment: openstack_env
  command: "{{item}}"
  with_items:
  # Identify v3
  - openstack endpoint create --region "{{region}}" identity public http://{{public_addr}}:5000/v3
  - openstack endpoint create --region "{{region}}" identity internal http://{{controller_addr}}:5000/v3
  - openstack endpoint create --region "{{region}}" identity admin http://{{controller_addr}}:35357/v3
  # Image
  - openstack endpoint create --region "{{region}}" image public http://{{public_addr}}:9292
  - openstack endpoint create --region "{{region}}" image internal http://{{controller_addr}}:9292
  - openstack endpoint create --region "{{region}}" image admin http://{{controller_addr}}:9292
  # Compute
  - openstack endpoint create --region "{{region}}" compute public http://{{public_addr}}:8774/v2.1/%\(tenant_id\)s
  - openstack endpoint create --region "{{region}}" compute internal http://{{controller_addr}}:8774/v2.1/%\(tenant_id\)s
  - openstack endpoint create --region "{{region}}" compute admin http://{{controller_addr}}:8774/v2.1/%\(tenant_id\)s
  # Network
  - openstack endpoint create --region "{{region}}" network public http://{{public_addr}}:9696
  - openstack endpoint create --region "{{region}}" network internal http://{{controller_addr}}:9696
  - openstack endpoint create --region "{{region}}" network admin http://{{controller_addr}}:9696
  # Heat
  - openstack endpoint create --region "{{region}}" orchestration public http://{{public_addr}}:8004/v1/%\(tenant_id\)s
  - openstack endpoint create --region "{{region}}" orchestration internal http://{{controller_addr}}:8004/v1/%\(tenant_id\)s
  - openstack endpoint create --region "{{region}}" orchestration admin http://{{controller_addr}}:8004/v1/%\(tenant_id\)s
  # Heat-cfn
  - openstack endpoint create --region "{{region}}" cloudformation public http://{{public_addr}}:8000/v1
  - openstack endpoint create --region "{{region}}" cloudformation internal http://{{controller_addr}}:8000/v1
  - openstack endpoint create --region "{{region}}" cloudformation admin http://{{controller_addr}}:8000/v1
  # Barbican
  - openstack endpoint create --region "{{region}}" key-manager public http://{{public_addr}}:9311
  - openstack endpoint create --region "{{region}}" key-manager internal http://{{controller_addr}}:9311
  - openstack endpoint create --region "{{region}}" key-manager admin http://{{controller_addr}}:9311
  # Magnum
  - openstack endpoint create --region "{{region}}" container public http://{{public_addr}}:9511/v1
  - openstack endpoint create --region "{{region}}" container internal http://{{controller_addr}}:9511/v1
  - openstack endpoint create --region "{{region}}" container admin http://{{controller_addr}}:9511/v1
  when: keystone_started|changed
  register: openstack_endpoint_ready
