- name: Installing MySQL Server
  action: apt pkg={{item}} state=installed
  with_items:
    - mysql-server
  register: mysql_installed

- name: Updating my.cnf
  copy: src=my.cnf
        dest=/etc/mysql/my.cnf
        owner=root
        group=root
        mode=0644
        backup=yes
  when: mysql_installed|changed
  register: my_cnf_updated

- name: Restarting MySQL
  service: name=mysql state=restarted
  when: my_cnf_updated|changed
  register: mysql_ready

- name: Creating OpenStack MySQL databases
  mysql_db: name={{item.db_name}} state=present
  when: mysql_ready|changed
  with_items: mysql_databases
  
- name: Creating OpenStack MySQL users 
  mysql_user:
    host="{{item.db_host}}"
    name="{{item.db_user}}"
    password="{{item.db_pass}}"
    priv="{{item.db_name}}.*:ALL,GRANT"
    state=present
  when: mysql_ready|changed
  with_items: mysql_databases
