- name: Installing Glance Server
  action: apt pkg={{item}} state=installed
  with_items:
    - glance
    - python-swiftclient
  register: glance_installed

- name: Stopping Glance API
  service: name=glance-api state=stopped
  when: glance_installed|changed
  register: api_stopped

- name: Stopping Glance Registry
  service: name=glance-registry state=stopped
  when: glance_installed|changed
  register: registry_stopped

- name: Removing non-used sqlite database
  file: path=/var/lib/glance/glance.sqlite state=absent
  when: glance_installed|changed
  register: glance_cleaned


- name: Updating glance-api.conf
  template: src=glance-api.conf
        dest=/etc/glance/glance-api.conf
        owner=glance
        group=glance
        mode=0644
        backup=yes
  when: api_stopped|changed and registry_stopped|changed and item.os_project == "glance"
  with_items: mysql_databases
  register: glancea_cfg_updated


- name: Updating glance-registry.conf
  template: src=glance-registry.conf
        dest=/etc/glance/glance-registry.conf
        owner=glance
        group=glance
        mode=0644
        backup=yes
  when: api_stopped|changed and registry_stopped|changed and item.os_project == "glance"
  with_items: mysql_databases
  register: glancer_cfg_updated


- name: Populating Glance Database
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
  when: glancea_cfg_updated|changed and glancer_cfg_updated|changed
  register: glance_populated

- name: Starting Glance API
  service: name=glance-api state=restarted
  when: glance_populated|changed
  register: api_started

- name: Starting Glance Registry
  service: name=glance-registry state=restarted
  when: glance_populated|changed
  register: registry_started


- name: Wait a bit until Glance starts up properly...
  pause: seconds=5
  when: api_started|changed and registry_started|changed
  register: glance_ready


